### PR TITLE
Update nupyprop tables: Issue57

### PR DESCRIPTION
**Pull request by dikgarg**
Updated nupyprop pexit.h5 file and removed no_regen data. The new pexit file replaced already existing version 3 pexit file.

### CODE REVIEW

**Review by Areustle — CHANGES_REQUESTED** [review]
These changes are in conflict with the main branch. Follow the instructions under "Resolve with Command Line" to resolve the conflicts.

**Comment by dikgarg** [comment]
I think I have resolved the merge conflict. But all of the automatic checks have failed. The error it is throwing is the following:
`configparser.DuplicateOptionError: While reading from PosixPath('setup.cfg') [line 71]: option 'nuspacesim.data.nuleptonsim_tables' in section 'options.package_data' already exists`

So seems like some conflict with the nuleptonsim tables, not sure how to resolve this.

**Comment by Areustle** [comment]
It looks like you haven't yet resolved the conflicts in the setup.cfg file. If you look at the diff https://github.com/NuSpaceSim/nuSpaceSim/pull/59/commits/4210615fd2ae95efd61e48af8ccbb92760a31c80 you can see the HEAD/MAIN decoration is still in there. Delete those lines before recommitting.

**Comment by dikgarg** [comment]
Okay, I fixed the issue and all the checks were also successful.

**Review by Areustle — APPROVED** [review]

**Pull request merged**
